//! 暴露给前端的 Tauri 命令。

use std::collections::{HashMap, HashSet};
use std::path::Path;
use std::time::{Duration, SystemTime};

use tauri::{AppHandle, Emitter, Manager, Url, WebviewUrl, WebviewWindowBuilder};

use crate::AppState;

/// 返回 sidecar 的 API base。None 表示开发模式（前端走 vite proxy 的 /api/v1）。
#[tauri::command]
pub fn get_api_base(state: tauri::State<'_, AppState>) -> Option<String> {
    // dev 模式不启 sidecar（后端跑 make server → vite proxy /api/v1）。
    // 直接返回代理地址，避免前端误判 sidecar 未就绪、空轮询 90s 才超时进工作台。
    if tauri::is_dev() {
        return Some("/api/v1".to_string());
    }
    state
        .sidecar
        .lock()
        .ok()?
        .as_ref()
        .map(|s| s.api_base())
}

const DOUYIN_URL: &str = "https://www.douyin.com/";
const MOBILE_UA: &str = "Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Mobile/15E148 Safari/604.1";
/// 抖音博主采集 webview 窗口标签（lib.rs 关窗事件据此发 cancelled）
pub const CAPTURE_WINDOW_LABEL: &str = "douyin-creator-capture";
/// yt-dlp 抖音提取器可用的最小匿名 cookie 集合（实测得出，均不含登录态）
const REQUIRED_COOKIES: [&str; 4] = ["ttwid", "s_v_web_id", "odin_tt", "passport_csrf_token"];
const AUTO_MARKER: &str = "# auto-generated by VideoMind";
const FRESH_SECS: u64 = 12 * 3600;
const HARVEST_LABEL: &str = "douyin-cookie-harvest";

/// 确保存在可用的抖音 cookie：
/// - 用户手动导入的文件（无自动标记）永不覆盖，直接返回
/// - 自动生成的文件 12 小时内视为新鲜
/// - 否则打开隐藏 webview 访问抖音，收割页面 JS 生成的匿名 cookie
#[tauri::command]
pub async fn ensure_douyin_cookies(app: AppHandle) -> Result<String, String> {
    let path = app
        .path()
        .app_data_dir()
        .map_err(|e| e.to_string())?
        .join("cookies")
        .join("douyin.txt");
    if let Ok(content) = std::fs::read_to_string(&path) {
        if !content.contains(AUTO_MARKER) {
            return Ok("manual".into()); // 用户导入的 cookie，不动
        }
        let age = std::fs::metadata(&path)
            .and_then(|m| m.modified())
            .ok()
            .and_then(|t| SystemTime::now().duration_since(t).ok());
        if matches!(age, Some(d) if d.as_secs() < FRESH_SECS) {
            return Ok("fresh".into());
        }
    }
    harvest_douyin_cookies(&app, &path).await
}

async fn harvest_douyin_cookies(app: &AppHandle, path: &Path) -> Result<String, String> {
    let url: Url = DOUYIN_URL.parse().map_err(|e| format!("{e}"))?;
    let _ = &url;
    let window = match app.get_webview_window(HARVEST_LABEL) {
        Some(w) => w,
        None => WebviewWindowBuilder::new(app, HARVEST_LABEL, WebviewUrl::External(url.clone()))
            .title("douyin-bootstrap")
            .visible(false)
            .initialization_script(
                // 防止隐藏页面里的视频出声
                "try{HTMLMediaElement.prototype.play=function(){this.muted=true;return Promise.resolve()}}catch(e){}",
            )
            .build()
            .map_err(|e| e.to_string())?,
    };

    let mut snapshot: Vec<(String, String)> = Vec::new();
    for i in 0..80 {
        // 每 500ms 轮询一次，最多 40s
        tauri::async_runtime::spawn_blocking(|| std::thread::sleep(Duration::from_millis(500)))
            .await
            .ok();
        let cookies = window.cookies().map_err(|e| e.to_string())?;
        snapshot = cookies
            .iter()
            .filter(|c| c.domain().map(|d| d.contains("douyin")).unwrap_or(false))
            .map(|c| (c.name().to_string(), c.value().to_string()))
            .collect();
        let names: HashSet<&str> = snapshot.iter().map(|(n, _)| n.as_str()).collect();
        if i % 20 == 19 {
            eprintln!("[douyin] 轮询 {}s: 已获取 {} 条 cookie", (i + 1) / 2, names.len());
        }
        if REQUIRED_COOKIES.iter().all(|r| names.contains(r)) {
            break;
        }
    }
    let _ = window.close();

    let names: HashSet<&str> = snapshot.iter().map(|(n, _)| n.as_str()).collect();
    let missing: Vec<&str> = REQUIRED_COOKIES
        .iter()
        .copied()
        .filter(|r| !names.contains(r))
        .collect();
    if !missing.is_empty() {
        return Err(format!("抖音 cookie 获取不完整，缺少: {}", missing.join(", ")));
    }

    if let Some(dir) = path.parent() {
        std::fs::create_dir_all(dir).map_err(|e| e.to_string())?;
    }
    let mut out = format!("# Netscape HTTP Cookie File\n{AUTO_MARKER}\n");
    for (name, value) in &snapshot {
        out.push_str(&format!(
            ".douyin.com\tTRUE\t/\tFALSE\t1893456000\t{name}\t{value}\n"
        ));
    }
    std::fs::write(path, out).map_err(|e| e.to_string())?;
    eprintln!("[douyin] 已自动获取 {} 条匿名 cookie", snapshot.len());
    Ok(format!("harvested:{}", snapshot.len()))
}

// ───────────────────────── 抖音博主主页采集（webview 方案） ─────────────────────────
//
// yt-dlp 的抖音提取器只认 /video/<id>，不实现用户页，旧版 aweme/post API 也已失效。
// 改用可见 webview 加载博主主页：页面自己会带签名请求 /aweme/v1/web/aweme/post，
// 注入脚本 hook 住响应、自动滚动翻页，凑够视频后经合成 URL 回传给 Rust，再交前端
// 批量采集（每条 /video/<id> yt-dlp 原生支持）。全程不算任何签名。

/// 注入到博主主页 webview 的采集脚本：hook fetch/XHR + 自动滚动 + 首屏 DOM 兜底。
/// limit 由调用方在脚本前设 window.__vmLimit 后再执行本段。
const CAPTURE_JS: &str = r#"(function(){
  if (window.__vmCollector) return; window.__vmCollector = true;
  var LIMIT = window.__vmLimit || 20;
  var ids = {}, doneSent = false;
  var xhrHits = 0, lastHasMore = null; // 诊断：aweme/post 命中次数 / 末次 has_more

  function banner(msg, bg){
    var b = document.getElementById('__vm_banner');
    if(!b){ b = document.createElement('div'); b.id='__vm_banner';
      b.style.cssText='position:fixed;top:0;left:0;right:0;z-index:2147483647;'
        +'background:'+(bg||'#1a73e8')+';color:#fff;font:13px/1.4 system-ui,sans-serif;'
        +'padding:8px 12px;text-align:center;box-shadow:0 2px 6px rgba(0,0,0,.3)';
      document.documentElement.appendChild(b); }
    b.textContent = msg;
  }
  function addList(list){
    if(!list) return;
    for(var i=0;i<list.length;i++){ var a=list[i]; if(a&&a.aweme_id){ ids[a.aweme_id]=true; } }
  }
  function consume(text, srcUrl){
    try{ var j=typeof text==='string'?JSON.parse(text):text;
      if(typeof j.has_more==='boolean') lastHasMore=j.has_more;
      var list=j.aweme_list||(j.aweme_post_mode_info&&j.aweme_post_mode_info.aweme_list)||(j.data&&j.data.aweme_list);
      if(list){ xhrHits++; addList(list); }
      else if(srcUrl&&(''+srcUrl).indexOf('/aweme/post')!==-1){
        // 主页视频接口结构可能嵌套不同：深度抠 aweme_id 兜底，确保不漏
        xhrHits++;
        (function walk(v,d){ if(!v||d>9) return; if(typeof v==='object'){ if(v.aweme_id) ids[v.aweme_id]=true; for(var k in v) walk(v[k],d+1); } })(j,0);
      }
    }catch(e){}
  }
  var seenUrls=[];
  function noteUrl(u){ try{ u=''+u; if(seenUrls.length<25 && seenUrls.indexOf(u)===-1) seenUrls.push(u); }catch(e){} }
  // 从 douyin SSR 全局里抠 aweme_id（fetch/XHR hook 没命中时也能拿首屏整页）
  function scrapeGlobals(){
    try{ var roots=[window._ROUTER_DATA,window._SSR_HYDRATED_DATA,window.__INITIAL_STATE__,window._SSR_DATA];
      (function walk(v,d){ if(!v||d>9) return; if(typeof v==='object'){
        if(v.aweme_id) ids[v.aweme_id]=true;
        for(var k in v){ walk(v[k],d+1); } } })(roots,0);
    }catch(e){}
  }
  // 1. hook fetch
  var _f=window.fetch;
  if(_f){ window.fetch=function(){
    var p=_f.apply(this,arguments);
    try{ var u=(arguments[0]&&(arguments[0].url||arguments[0]))||''; noteUrl(u);
      if((''+u).indexOf('aweme')!==-1){ p.then(function(r){ try{r.clone().text().then(function(t){consume(t,u);}).catch(function(){});}catch(e){} return r;}).catch(function(){}); }
    }catch(e){}
    return p;
  }; }
  // 2. hook XHR
  var _o=XMLHttpRequest.prototype.open, _s=XMLHttpRequest.prototype.send;
  XMLHttpRequest.prototype.open=function(m,u){ this.__vmUrl=u; noteUrl(u); return _o.apply(this,arguments); };
  XMLHttpRequest.prototype.send=function(){ var x=this;
    x.addEventListener('load',function(){ try{ var u=''+x.__vmUrl;
      if(u.indexOf('aweme')!==-1) consume(x.responseText,u); }catch(e){} });
    return _s.apply(this,arguments);
  };
  // 3. DOM 兜底：只在博主作品网格容器内取链接，避免抓到侧栏/推荐的他人视频。
  //    找不到已知容器就跳过——主源是 /aweme/post 响应，DOM 只作补充。
  function scrapeDom(){
    var root = document.querySelector('[data-e2e="scroll-list"]')
      || document.querySelector('[data-e2e="user-tab-list"]')
      || document.querySelector('[data-e2e="user-post-list"]');
    if(!root) return;
    var l = root.querySelectorAll('a[href*="/video/"]');
    for(var i=0;i<l.length;i++){ var m=(''+l[i].getAttribute('href')).match(/\/video\/(\d+)/); if(m) ids[m[1]]=true; }
  }
  function count(){ var n=0,k; for(k in ids) n++; return n; }
  function finish(reason){ if(doneSent) return; doneSent=true;
    var all=[]; for(var k in ids) all.push('https://www.douyin.com/video/'+k);
    var urls = all.slice(0, LIMIT); // 尊重用户设定的条数上限
    banner('VideoMind：'+(urls.length?('抓取完成，共 '+urls.length+' 条'):'未抓到视频')+'，正在导入…', urls.length?'#0b8043':'#c0392b');
    var more = lastHasMore===null?'na':(lastHasMore?1:0);
    var seen = seenUrls.filter(function(u){return /aweme|post|user|video/i.test(u);}).slice(0,15).join('\n  ');
    location.assign('https://videomind.capture/done?n='+urls.length
      +'&j='+encodeURIComponent(JSON.stringify(urls))
      +'&reason='+reason+'&hits='+xhrHits+'&more='+more
      +'&lim='+LIMIT
      +'&dom='+document.querySelectorAll('a[href*="/video/"]').length
      +'&seen='+encodeURIComponent(seen)
      +'&href='+encodeURIComponent(location.href));
  }
  // 滚到最底以触发懒加载：先滚 window，再找最大的内层 overflow 容器（抖音可能把列表放里面）
  function scrollToLoadMore(){
    window.scrollTo(0, document.body.scrollHeight);
    document.documentElement.scrollTop = document.documentElement.scrollHeight;
    var all=document.getElementsByTagName('*'), best=null, bestRemain=0;
    for(var i=0;i<all.length;i++){ var el=all[i];
      var remain=el.scrollHeight-el.clientHeight-el.scrollTop;
      if(remain>bestRemain && el.scrollHeight>el.clientHeight+200){ bestRemain=remain; best=el; } }
    if(best) best.scrollTop=best.scrollHeight;
  }
  // 4. 自动滚动
  var stagn=0, ticks=0;
  function tick(){
    if(++ticks>240){ finish('timeout'); return; } // 硬上限 ~6 分钟（含登录/验证时间）
    scrapeDom(); var c=count();
    if(c>0){
      banner('VideoMind 采集中：已发现 '+c+' / '+LIMIT+' 条（接口命中 '+xhrHits+'）');
    } else if(ticks>3){
      banner('VideoMind：未发现视频——如弹出登录/验证请在窗口内完成，完成后自动继续抓取', '#c0392b');
    } else {
      banner('VideoMind 采集中：正在加载…');
    }
    if(c>=LIMIT){ finish('limit'); return; }
    if(lastHasMore===false && c>0){ finish('nomore'); return; } // 接口明确没更多了
    scrollToLoadMore();
    setTimeout(function(){ scrapeDom();
      var c2=count();
      // 只有抓到过视频（c>0）后才用 stagn 判“到底”；c==0 多半是登录墙，一直等用户处理
      if(c>0 && c2===c){ if(++stagn>=10) finish('stagn'); } else stagn=0;
      tick();
    }, 1500);
  }
  setTimeout(function(){ scrapeDom(); scrapeGlobals(); tick(); }, 1800);
})();"#;

#[derive(Clone, serde::Serialize)]
struct CaptureDone {
    count: u32,
    urls: Vec<String>,
}

/// 从分享口令/短链/主页链接里抽出桌面版博主主页 URL（www.douyin.com/user/<sec_uid>）。
fn resolve_creator_url(raw: &str) -> Result<String, String> {
    // 1. 口令文本里取第一个 http(s) 链接
    let input = find_http_url(raw);
    let parsed = Url::parse(input).map_err(|e| format!("链接格式无效: {e}"))?;
    let host = parsed.host_str().unwrap_or("").to_lowercase();

    // 2. 短链跟随重定向（v.douyin.com → iesdouyin.com/share/user/<sec_uid>）
    let final_url = if host == "v.douyin.com" || host.ends_with(".amemv.com") {
        let client = reqwest::blocking::Client::builder()
            .redirect(reqwest::redirect::Policy::limited(10))
            .user_agent(MOBILE_UA)
            .build()
            .map_err(|e| e.to_string())?;
        let resp = client
            .get(input)
            .send()
            .map_err(|e| format!("短链解析失败: {e}"))?;
        resp.url().to_string()
    } else {
        input.to_string()
    };

    // 3. 抠 sec_uid，重写成桌面 SPA 主页
    let parsed = Url::parse(&final_url).map_err(|e| e.to_string())?;
    let segs: Vec<&str> = parsed
        .path_segments()
        .map(|mut p| p.filter(|s| !s.is_empty()).collect())
        .unwrap_or_default();
    let sec = match segs.as_slice() {
        ["share", "user", s, ..] | ["user", s, ..] => Some(*s),
        _ => None,
    }
    .ok_or_else(|| "不是抖音博主主页链接（未找到 sec_uid）".to_string())?;
    Ok(format!("https://www.douyin.com/user/{sec}"))
}

/// 在文本里定位第一个 http(s) 链接（到空白或中文字符截断）；无则原样返回。
fn find_http_url(s: &str) -> &str {
    let lower = s.to_lowercase();
    let start = match lower.find("http") {
        Some(i) => i,
        None => return s.trim(),
    };
    let bytes = s.as_bytes();
    let mut end = start;
    let mut i = start;
    while i < bytes.len() {
        let c = match s[i..].chars().next() {
            Some(c) => c,
            None => break,
        };
        if c.is_whitespace()
            || ('\u{4e00}'..='\u{9fff}').contains(&c)
            || "，。；：、（）()<>\"".contains(c)
        {
            break;
        }
        i += c.len_utf8();
        end = i;
    }
    s[start..end].trim_end_matches(".,;!?\"'")
}

/// 把 webview 的抖音匿名 cookie 落盘成 Netscape 文件（供后续逐条 yt-dlp 下载用）。
fn persist_douyin_cookies(window: &tauri::WebviewWindow, path: &Path) {
    let cookies = match window.cookies() {
        Ok(c) => c,
        Err(_) => return,
    };
    let snapshot: Vec<(String, String)> = cookies
        .iter()
        .filter(|c| c.domain().map(|d| d.contains("douyin")).unwrap_or(false))
        .map(|c| (c.name().to_string(), c.value().to_string()))
        .collect();
    if snapshot.is_empty() {
        return;
    }
    if let Some(dir) = path.parent() {
        if std::fs::create_dir_all(dir).is_err() {
            return;
        }
    }
    let mut out = String::from("# Netscape HTTP Cookie File\n# refreshed by creator capture\n");
    for (name, value) in &snapshot {
        out.push_str(&format!(
            ".douyin.com\tTRUE\t/\tFALSE\t1893456000\t{name}\t{value}\n"
        ));
    }
    let _ = std::fs::write(path, out);
}

/// 打开可见 webview 加载博主主页，注入采集脚本；凑够视频后脚本经合成 URL 回传，
/// on_navigation 拦截 → emit('douyin-capture-done', {count, urls}) → 关窗。
/// 用户提前关窗则由 lib.rs 的 on_window_event emit 'douyin-capture-cancelled'。
#[tauri::command]
pub async fn collect_douyin_creator(
    app: AppHandle,
    url: String,
    limit: Option<usize>,
) -> Result<(), String> {
    let limit = limit.unwrap_or(20).clamp(1, 100);
    // 重置“程序主动关窗”标志（区分采集完成 vs 用户取消）
    if let Some(s) = app.try_state::<crate::AppState>() {
        s.capture_done.store(false, std::sync::atomic::Ordering::SeqCst);
    }
    let url_clone = url.clone();
    let desktop = tauri::async_runtime::spawn_blocking(move || {
        resolve_creator_url(&url_clone)
    })
    .await
    .map_err(|e| format!("{e}"))??;
    eprintln!("[douyin-capture] 开始: input={url} -> desktop={desktop} limit={limit}");

    let cookie_path = app
        .path()
        .app_data_dir()
        .map_err(|e| e.to_string())?
        .join("cookies")
        .join("douyin.txt");
    // 采集窗固定 data 目录：登录/验证一次后 cookie 持久化，以后不用重复登录
    let webview_data = app
        .path()
        .app_data_dir()
        .map_err(|e| e.to_string())?
        .join("webview-data");

    // 关掉可能残留的同名窗口
    if let Some(w) = app.get_webview_window(CAPTURE_WINDOW_LABEL) {
        let _ = w.close();
        std::thread::sleep(Duration::from_millis(150));
    }

    let init_js = format!("window.__vmLimit={};{}", limit, CAPTURE_JS);
    let target: Url = desktop
        .parse()
        .map_err(|e| format!("目标 URL 无效: {e}"))?;

    let app_for_nav = app.clone();
    let cookie_path_for_nav = cookie_path.clone();
    WebviewWindowBuilder::new(&app, CAPTURE_WINDOW_LABEL, WebviewUrl::External(target))
        .title("VideoMind · 抖音博主采集")
        .inner_size(420.0, 780.0)
        .min_inner_size(360.0, 540.0)
        .data_directory(webview_data)
        .initialization_script(&init_js)
        .on_navigation(move |nav_url| {
            if nav_url.host_str() == Some("videomind.capture") {
                let pairs: HashMap<String, String> = nav_url
                    .query_pairs()
                    .map(|(k, v)| (k.to_string(), v.to_string()))
                    .collect();
                if nav_url.path() == "/done" {
                    let n: u32 = pairs.get("n").and_then(|s| s.parse().ok()).unwrap_or(0);
                    let urls: Vec<String> = pairs
                        .get("j")
                        .and_then(|j| serde_json::from_str(j).ok())
                        .unwrap_or_default();
                    eprintln!(
                        "[douyin-capture] 采集结束: count={} reason={:?} xhr_hits={:?} has_more={:?} | limit={:?} dom_links={:?}\n  href={:?}\n  seen:\n  {}",
                        n,
                        pairs.get("reason").map(String::as_str).unwrap_or("?"),
                        pairs.get("hits").map(String::as_str).unwrap_or("?"),
                        pairs.get("more").map(String::as_str).unwrap_or("?"),
                        pairs.get("lim").map(String::as_str).unwrap_or("?"),
                        pairs.get("dom").map(String::as_str).unwrap_or("?"),
                        pairs.get("href").map(String::as_str).unwrap_or("?"),
                        pairs.get("seen").map(String::as_str).unwrap_or("(none)"),
                    );
                    // 顺带刷新 cookie 文件（best-effort，给后续逐条下载用）
                    if let Some(w) = app_for_nav.get_webview_window(CAPTURE_WINDOW_LABEL) {
                        persist_douyin_cookies(&w, &cookie_path_for_nav);
                    }
                    let _ = app_for_nav.emit(
                        "douyin-capture-done",
                        CaptureDone { count: n.max(urls.len() as u32), urls },
                    );
                    // 标记“程序主动关窗”，lib.rs 据此不发 cancelled
                    if let Some(s) = app_for_nav.try_state::<crate::AppState>() {
                        s.capture_done.store(true, std::sync::atomic::Ordering::SeqCst);
                    }
                    if let Some(w) = app_for_nav.get_webview_window(CAPTURE_WINDOW_LABEL) {
                        let _ = w.close();
                    }
                }
                return false; // 阻止真跳转到合成 URL
            }
            true
        })
        .build()
        .map_err(|e| format!("打开采集窗口失败: {e}"))?;
    Ok(())
}
