//! 暴露给前端的 Tauri 命令。

use std::collections::HashSet;
use std::path::Path;
use std::time::{Duration, SystemTime};

use tauri::{AppHandle, Manager, Url, WebviewUrl, WebviewWindowBuilder};

use crate::AppState;

/// 返回 sidecar 的 API base。None 表示开发模式（前端走 vite proxy 的 /api/v1）。
#[tauri::command]
pub fn get_api_base(state: tauri::State<'_, AppState>) -> Option<String> {
    state
        .sidecar
        .lock()
        .ok()?
        .as_ref()
        .map(|s| s.api_base())
}

/// 启动阶段（starting | extracting | ready），splash 据此切换文案。
#[tauri::command]
pub fn get_boot_stage(state: tauri::State<'_, AppState>) -> String {
    state
        .boot_stage
        .lock()
        .map(|s| s.clone())
        .unwrap_or_else(|_| "starting".into())
}

const DOUYIN_URL: &str = "https://www.douyin.com/";
/// yt-dlp 抖音提取器可用的最小匿名 cookie 集合（实测得出，均不含登录态）
const REQUIRED_COOKIES: [&str; 4] = ["ttwid", "s_v_web_id", "odin_tt", "passport_csrf_token"];
const AUTO_MARKER: &str = "# auto-generated by VideoMind";
const FRESH_SECS: u64 = 12 * 3600;
const HARVEST_LABEL: &str = "douyin-cookie-harvest";

/// 确保存在可用的抖音 cookie：
/// - 用户手动导入的文件（无自动标记）永不覆盖，直接返回
/// - 自动生成的文件 12 小时内视为新鲜
/// - 否则打开隐藏 webview 访问抖音，收割页面 JS 生成的匿名 cookie
#[tauri::command]
pub async fn ensure_douyin_cookies(app: AppHandle) -> Result<String, String> {
    let path = app
        .path()
        .app_data_dir()
        .map_err(|e| e.to_string())?
        .join("cookies")
        .join("douyin.txt");
    if let Ok(content) = std::fs::read_to_string(&path) {
        if !content.contains(AUTO_MARKER) {
            return Ok("manual".into()); // 用户导入的 cookie，不动
        }
        let age = std::fs::metadata(&path)
            .and_then(|m| m.modified())
            .ok()
            .and_then(|t| SystemTime::now().duration_since(t).ok());
        if matches!(age, Some(d) if d.as_secs() < FRESH_SECS) {
            return Ok("fresh".into());
        }
    }
    harvest_douyin_cookies(&app, &path).await
}

async fn harvest_douyin_cookies(app: &AppHandle, path: &Path) -> Result<String, String> {
    let url: Url = DOUYIN_URL.parse().map_err(|e| format!("{e}"))?;
    let _ = &url;
    let window = match app.get_webview_window(HARVEST_LABEL) {
        Some(w) => w,
        None => WebviewWindowBuilder::new(app, HARVEST_LABEL, WebviewUrl::External(url.clone()))
            .title("douyin-bootstrap")
            .visible(false)
            .initialization_script(
                // 防止隐藏页面里的视频出声
                "try{HTMLMediaElement.prototype.play=function(){this.muted=true;return Promise.resolve()}}catch(e){}",
            )
            .build()
            .map_err(|e| e.to_string())?,
    };

    let mut snapshot: Vec<(String, String)> = Vec::new();
    for i in 0..80 {
        // 每 500ms 轮询一次，最多 40s
        tauri::async_runtime::spawn_blocking(|| std::thread::sleep(Duration::from_millis(500)))
            .await
            .ok();
        let cookies = window.cookies().map_err(|e| e.to_string())?;
        snapshot = cookies
            .iter()
            .filter(|c| c.domain().map(|d| d.contains("douyin")).unwrap_or(false))
            .map(|c| (c.name().to_string(), c.value().to_string()))
            .collect();
        let names: HashSet<&str> = snapshot.iter().map(|(n, _)| n.as_str()).collect();
        if i % 20 == 19 {
            eprintln!("[douyin] 轮询 {}s: 已获取 {} 条 cookie", (i + 1) / 2, names.len());
        }
        if REQUIRED_COOKIES.iter().all(|r| names.contains(r)) {
            break;
        }
    }
    let _ = window.close();

    let names: HashSet<&str> = snapshot.iter().map(|(n, _)| n.as_str()).collect();
    let missing: Vec<&str> = REQUIRED_COOKIES
        .iter()
        .copied()
        .filter(|r| !names.contains(r))
        .collect();
    if !missing.is_empty() {
        return Err(format!("抖音 cookie 获取不完整，缺少: {}", missing.join(", ")));
    }

    if let Some(dir) = path.parent() {
        std::fs::create_dir_all(dir).map_err(|e| e.to_string())?;
    }
    let mut out = format!("# Netscape HTTP Cookie File\n{AUTO_MARKER}\n");
    for (name, value) in &snapshot {
        out.push_str(&format!(
            ".douyin.com\tTRUE\t/\tFALSE\t1893456000\t{name}\t{value}\n"
        ));
    }
    std::fs::write(path, out).map_err(|e| e.to_string())?;
    eprintln!("[douyin] 已自动获取 {} 条匿名 cookie", snapshot.len());
    Ok(format!("harvested:{}", snapshot.len()))
}
